models/history.py
import arrow

from firebase_config import firebase_db
from firebase_admin import firestore


class History:
    def __init__(self, id=None, abstrak=None, kata_kunci=None, probabilitas=None, kelompok_bidang_keahlian=None, tanggal_inferensi=None, top_similarity=None):
        self.id = id
        self.abstrak = abstrak
        self.kata_kunci = kata_kunci
        self.probabilitas = probabilitas
        self.kelompok_bidang_keahlian = kelompok_bidang_keahlian
        self.tanggal_inferensi = tanggal_inferensi  
        self.top_similarity = top_similarity


    def save(self, id):
        _, doc = firebase_db.collection('users').document(id).collection('histories').add({
            'abstrak': self.abstrak,
            'kata_kunci': self.kata_kunci,
            'probabilitas': self.probabilitas,
            'kelompok_bidang_keahlian': self.kelompok_bidang_keahlian,
            'tanggal_inferensi': self.tanggal_inferensi,
            'top_similarity': self.top_similarity
        })
        
        self.id = doc.id

        return self
    

    def delete(self, id):
        firebase_db.collection('users').document(id).collection('histories').document(self.id).delete()

        return self
    

    @staticmethod
    def fetch(id):
        histories = firebase_db.collection('users').document(id).collection('histories').order_by("tanggal_inferensi", direction=firestore.Query.DESCENDING).stream()

        datas = []
        for history in histories:
            data = history.to_dict()
            datas.append({
                'id': history.id,
                'abstrak': data['abstrak'],
                'kata_kunci': data['kata_kunci'],
                'probabilitas': dict(sorted(data['probabilitas'].items(), key=lambda item: item[1], reverse=True)),
                'kelompok_bidang_keahlian': data['kelompok_bidang_keahlian'],
                'tanggal_inferensi': arrow.get(data['tanggal_inferensi']).to('Asia/Jakarta').format('dddd, DD-MM-YYYY HH:mm:ss', locale='id_ID'),
                'top_similarity': data['top_similarity']
            })

        return datas

models/user.py
import arrow

from flask_login import UserMixin
from firebase_config import firebase_db
from firebase_admin import firestore


class User(UserMixin):
    def __init__(self, id=None, nama=None, email=None, role=None, registered_at=None, inactive=None):
        self.id = id
        self.nama = nama
        self.email = email
        self.role = role
        self.registered_at = registered_at
        self.inactive = inactive


    def update(self):
        firebase_db.collection('users').document(self.id).update({
            'inactive': self.inactive,
        })

        return self
    

    @staticmethod
    def fetch():
        users = firebase_db.collection('users').where('role', '==', 'pengguna').order_by("registered_at", direction=firestore.Query.DESCENDING).stream()

        datas = []
        for user in users:
            data = user.to_dict()
            datas.append({
                'id': user.id,
                'nama': data['nama'],
                'email': data['email'],
                'role': data['role'],
                'inactive': data['inactive'],
                'registered_at': arrow.get(data['registered_at']).to('Asia/Jakarta').format('dddd, DD-MM-YYYY HH:mm:ss', locale='id_ID'),
                'status_badge': 'danger' if data['inactive'] == "1" else 'success'
            })

        return datas

views/auth.py
import json

from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from requests.exceptions import HTTPError
from firebase_config import firebase_auth, firebase_db
from flask_login import logout_user, login_user
from middleware import load_user
from pytz import timezone


auth = Blueprint('auth', __name__, template_folder='templates')
tz = timezone('Asia/Jakarta')

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        nama = request.form['nama']
        email = request.form['email']
        password = request.form['password']
        confirm_password = request.form['confirm_password']

        if not nama or not email or not password or not confirm_password:
            flash(('Pendaftaran Gagal', 'Semua isian harus diisi'), 'error')
            return render_template('auth/sign_up.html')
        
        if not email.endswith('pnj.ac.id'):
            flash(('Pendaftaran Gagal', 'Harus menggunakan email Politeknik Negeri Jakarta'), 'error')
            return render_template('auth/sign_up.html')
        
        if password != confirm_password:
            flash(('Pendaftaran Gagal', 'Password dan konfirmasi password tidak sama'), 'error')
            return render_template('auth/sign_up.html')
        
        try:
            user = firebase_auth.create_user_with_email_and_password(email, password)

            data = {
                'nama': nama,
                'email': email,
                'role': 'pengguna',
                'registered_at': datetime.now(tz),
                'inactive': '0'
            }

            firebase_db.collection('users').document(user['localId']).set(data)

            firebase_auth.send_email_verification(user['idToken'])
            flash(('Pendaftaran Diproses', 'Periksa email untuk verifikasi akun'), 'success')

        except HTTPError as e:
            message = json.loads(e.strerror)['error']['message']

            if 'WEAK_PASSWORD' in message:
                message = 'Password minimal 6 karakter'

            if 'EMAIL_EXISTS' in message:
                message = 'Email sudah terdaftar'

            flash(('Pendaftaran Gagal', message), 'error')

    return render_template('auth/sign_up.html')


@auth.route('/sign-in', methods=['GET', 'POST'])
def sign_in():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        if not email or not password:
            flash(('Masuk Gagal', 'Semua isian harus diisi'), 'error')
            return render_template('auth/sign_in.html')
        
        try:
            user = firebase_auth.sign_in_with_email_and_password(email, password)
            user_info = firebase_auth.get_account_info(user['idToken'])['users'][0]

            if user_info['emailVerified'] == False:
                flash(('Masuk Gagal', 'Email belum diverifikasi'), 'error')
                return render_template('auth/sign_in.html')

        except HTTPError as e:
            message = json.loads(e.strerror)['error']['message']

            if 'INVALID_LOGIN_CREDENTIALS' in message:
                message = 'Email atau password salah'

            flash(('Masuk Gagal', message), 'error')
            return render_template('auth/sign_in.html')
        
        except Exception as e:
            flash(('Masuk Gagal', 'Server sedang bermasalah'), 'error')
            return render_template('auth/sign_in.html')
        
        user_id = user_info['localId']
        user = load_user(user_id)

        if user.inactive == "1":
            flash(('Masuk Gagal', 'Akun anda dinonaktifkan oleh admin'), 'error')
            return render_template('auth/sign_in.html')

        if user:
            login_user(user)
        
            if user.role == 'admin':
                return redirect(url_for('dashboard.lecturer'))
            
            elif user.role == "pengguna":
                return redirect(url_for('dashboard.classifier'))

    return render_template('auth/sign_in.html')


@auth.route('/reset-password', methods=['GET', 'POST'])
def reset_password():
    if request.method == 'POST':
        email = request.form['email']

        if not email:
            flash(('Reset Password Gagal', 'Email harus diisi'), 'error')
            return render_template('auth/reset_password.html')
        
        try: 
            firebase_auth.send_password_reset_email(email)
            flash(('Reset Password Diproses', 'Periksa email untuk reset password'), 'success')

        except HTTPError as e:
            message = json.loads(e.strerror)['error']['message']

            if 'INVALID_EMAIL' in message:
                message = 'Email tidak ditemukan' 

            flash(('Reset Password Gagal', message), 'error')
        
        except Exception as e:
            flash(('Reset Password Gagal', 'Server sedang bermasalah'), 'error')

    return render_template('auth/reset_password.html')


@auth.route('/sign-out')
def sign_out():
    logout_user()
    return redirect(url_for('auth.sign_in'))

views/classifier.py
from flask import request, Blueprint, jsonify, current_app
from middleware import role_required
from models.lecturer import Lecturer
from models.history import History
from datetime import datetime
from flask_login import current_user
from pytz import timezone


classifier = Blueprint('classifier', __name__, template_folder='templates', url_prefix='/dashboard/classifier')
tz = timezone('Asia/Jakarta')

@classifier.route('/inference', methods=['POST'])
@role_required('pengguna')
def inference():
    abstrak = request.get_json().get('abstrak')
    kata_kunci = request.get_json().get('kata_kunci')
    klasifikasi = request.get_json().get('klasifikasi')
    rekomendasi = request.get_json().get('rekomendasi')

    try:
        text = current_app.inference.text_processing(abstrak, kata_kunci)

        if klasifikasi:
            probs, kbk = current_app.inference.classification(text)
            lecturers = Lecturer.fetch(kelompok_bidang_keahlian=kbk)

        else:
            probs = {}
            kbk = ""
            lecturers = []

        if rekomendasi:
            recommended = current_app.inference.content_based_filtering(text)

        else:
            recommended = []

        history = History(abstrak=abstrak, kata_kunci=kata_kunci, probabilitas=probs, kelompok_bidang_keahlian=kbk, tanggal_inferensi=datetime.now(tz), top_similarity=recommended)
        history.save(current_user.id)

        return jsonify(message={'probs': probs, 'lecturers': lecturers, 'kbk': kbk, 'top_similarity': recommended}, status="success"), 200
    
    except Exception as e:
        return jsonify(message={'error': 'Server error'}, status="error"), 500

views/dashboard.py
from flask import Blueprint, render_template
from middleware import role_required
from models.lecturer import Lecturer
from models.user import User
from models.history import History


dashboard = Blueprint('dashboard', __name__, template_folder='templates', url_prefix='/dashboard')

@dashboard.route('/lecturer', methods=['GET'])
@role_required('admin')
def lecturer():
    lecturers = Lecturer.fetch()
    return render_template('dashboard/lecturer.html', page="lecturer", lecturers=lecturers)


@dashboard.route('/user', methods=['GET'])
@role_required('admin')
def user():
    users = User.fetch()
    return render_template('dashboard/user.html', page="user", users=users)


@dashboard.route('/classifier', methods=['GET'])
@role_required('pengguna')
def classifier():
    return render_template('dashboard/classifier.html', page="classifier")


@dashboard.route('/history/<string:id>', methods=['GET'])
@role_required('admin', 'pengguna')
def history(id):
    histories = History.fetch(id)
    return render_template('dashboard/history.html', page="history", histories=histories)


@dashboard.route('/file', methods=['GET'])
@role_required('pengguna')
def file():
    return render_template('dashboard/file.html', page="file")

views/file.py
import io


from flask import redirect, Blueprint, request, url_for, flash, send_file
from docx import Document

file = Blueprint('file', __name__, template_folder='templates', url_prefix='/dashboard/file')

@file.route('/ekspor', methods=['POST'])
def ekspor():
    nama = request.form['nama']
    nim = request.form['nim']
    file_type = request.form['file_type']

    data = request.form.to_dict()

    doc = Document(f'resources/{file_type}.docx')

    try:
        for p in doc.paragraphs:
            for key, value in data.items():
                if f'{{{{{key}}}}}' in p.text:
                    p.text = p.text.replace(f'{{{{{key}}}}}', value)

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        return send_file(buffer, as_attachment=True, download_name=f'{file_type}_{nama}_{nim}.docx', mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document')

    except Exception as e:
        flash(('Ekspor Berkas Gagal', 'Berkas gagal diekspor'), 'error')

views/history.py
from flask import Blueprint, request, redirect, url_for, flash
from middleware import role_required
from models.history import History
from flask_login import current_user


history = Blueprint('history', __name__, template_folder='templates', url_prefix='/dashboard/history')

@history.route('/delete', methods=['POST'])
@role_required('pengguna')
def delete():
    id = request.form['id']

    try:
        history = History(id=id)
        history.delete(current_user.id)

        flash(('Hapus Riwayat Sukses', 'Riwayat berhasil dihapus'), 'success')

    except Exception as e:
        flash(('Hapus Riwayat Gagal', 'Terjadi kesalahan server saat menghapus'), 'error')
        
    return redirect(url_for('dashboard.history', id=current_user.id))

views/inference.py
from flask import request, Blueprint, jsonify, current_app
from middleware import role_required
from models.lecturer import Lecturer
from models.history import History
from datetime import datetime
from flask_login import current_user
from pytz import timezone


inference = Blueprint('inference', __name__, template_folder='templates', url_prefix='/dashboard/inference')
tz = timezone('Asia/Jakarta')

@inference.route('/', methods=['POST'])
@role_required('pengguna')
def index():
    abstrak = request.get_json().get('abstrak')
    kata_kunci = request.get_json().get('kata_kunci')
    klasifikasi = request.get_json().get('klasifikasi')
    rekomendasi = request.get_json().get('rekomendasi')

    try:
        text = current_app.inference_utils.text_processing(abstrak, kata_kunci)

        if klasifikasi:
            probs, kbk = current_app.inference_utils.classification(text)
            lecturers = Lecturer.fetch(kelompok_bidang_keahlian=kbk) 

        else:
            probs = ""
            kbk = ""
            lecturers = ""

        if rekomendasi:
            recommended = current_app.inference_utils.content_based_filtering(text)
            
        else:
            recommended = ""

        history = History(abstrak=abstrak, kata_kunci=kata_kunci, probabilitas=probs, kelompok_bidang_keahlian=kbk, tanggal_inferensi=datetime.now(tz), top_similarity=recommended)
        history.save(current_user.id)

        return jsonify(message={'probs': probs, 'lecturers': lecturers, 'kbk': kbk, 'top_similarity': recommended}, status="success"), 200
    
    except Exception as e:
        return jsonify(message={'error': 'Server error'}, status="error"), 500

views/lecturer.py
from models.lecturer import Lecturer
from flask import Blueprint, request, redirect, url_for, flash
from middleware import role_required
from firebase_config import storage_upload_file, storage_delete_file


lecturer = Blueprint('lecturer', __name__, template_folder='templates', url_prefix='/dashboard/lecturer')

@lecturer.route('/create', methods=['POST'])
@role_required('admin')
def create():
    nama = request.form['nama']
    kbk = request.form['kbk']

    try:
        foto = storage_upload_file(request.files['foto'], 'lecturers')
        lecturer = Lecturer(nama=nama, kelompok_bidang_keahlian=kbk, foto=foto)
        lecturer.save()
        
        flash(('Tambah Data Sukses', 'Data dosen berhasil ditambahkan'), 'success')

    except Exception as e:
        flash(('Tambah Data Gagal', 'Terjadi kesalahan server saat menambahkan'), 'error')
        
    return redirect(url_for('dashboard.lecturer'))


@lecturer.route('/update', methods=['POST'])
@role_required('admin')
def update():
    id = request.form['id']
    nama = request.form['nama']
    kbk = request.form['kbk']
    foto = request.form['prev_foto']
    
    if request.files['foto'].filename != '':
        storage_delete_file(foto)
        foto = storage_upload_file(request.files['foto'], 'lecturers')

    try:
        lecturer = Lecturer(id=id, nama=nama, kelompok_bidang_keahlian=kbk, foto=foto)
        lecturer.update()

        flash(('Perbarui Data Sukses', 'Data dosen berhasil diperbarui'), 'success')

    except Exception as e:
        flash(('Perbarui Data Gagal', 'Terjadi kesalahan server saat memperbarui'), 'error')
        
    return redirect(url_for('dashboard.lecturer'))

@lecturer.route('/delete', methods=['POST'])
@role_required('admin')
def delete():
    id = request.form['id']
    foto = request.form['foto']

    try:
        lecturer = Lecturer(id=id, foto=foto)
        lecturer.delete()
        storage_delete_file(lecturer.foto)

        flash(('Hapus Data Sukses', 'Data dosen berhasil dihapus'), 'success')

    except Exception as e:
        flash(('Hapus Data Gagal', 'Terjadi kesalahan server saat menghapus'), 'error')
        
    return redirect(url_for('dashboard.lecturer'))

views/user.py
from flask import Blueprint, request, redirect, url_for, flash
from middleware import role_required
from models.user import User


user = Blueprint('user', __name__, template_folder='templates', url_prefix='/dashboard/user')

@user.route('/update', methods=['POST'])
@role_required('admin')
def update():
    id = request.form['id']
    status = request.form['status']

    try:
        user = User(id=id, inactive=status)
        user.update()

        flash(('Perbarui Status Sukses', 'Status pengguna berhasil diperbarui'), 'success')

    except Exception as e:
        flash(('Perbarui Status Gagal', 'Terjadi kesalahan server saat memperbarui'), 'error')
        
    return redirect(url_for('dashboard.user'))

templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>{% block title %}{% endblock title %}</title>

    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/favicon.png') }}"
    />

    <script
      defer
      src="{{ url_for('static', filename='plugins/fontawesome/js/all.min.js') }}"
    ></script>

    <link
      id="theme-style"
      rel="stylesheet"
      href="{{ url_for('static', filename='css/portal.css') }}"
    />

    <link
      rel="manifest"
      href="{{ url_for('static', filename='manifest.json') }}"
    />

    {% block style %} {% endblock style %}
  </head>

  <body class="app">
    <div class="overlay d-none"></div>
    <div class="spinner d-none"></div>

    <header class="app-header fixed-top">
      <div class="app-header-inner">
        <div class="container-fluid py-2">
          <div class="app-header-content">
            <div class="row justify-content-between align-items-center">
              <div class="col-auto">
                <a
                  id="sidepanel-toggler"
                  class="sidepanel-toggler d-inline-block d-xl-none"
                  href="#"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="30"
                    height="30"
                    viewBox="0 0 30 30"
                    role="img"
                  >
                    <title>Menu</title>
                    <path
                      stroke="currentColor"
                      stroke-linecap="round"
                      stroke-miterlimit="10"
                      stroke-width="2"
                      d="M4 7h22M4 15h22M4 23h22"
                    ></path>
                  </svg>
                </a>
              </div>

              <div class="app-utilities col-auto mt-2">
                <div class="app-utility-item app-user-dropdown dropdown">
                  <a
                    class="dropdown-toggle text-unmuted small"
                    id="user-dropdown-toggle"
                    data-bs-toggle="dropdown"
                    href=""
                    role="button"
                    aria-expanded="false"
                  >
                    <b>{{ current_user.nama }}</b>
                  </a>
                  <ul
                    class="dropdown-menu"
                    aria-labelledby="user-dropdown-toggle"
                  >
                    <li>
                      <a
                        class="dropdown-item"
                        href="{{ url_for('auth.sign_out') }}"
                        >Log Out</a
                      >
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div id="app-sidepanel" class="app-sidepanel">
        <div id="sidepanel-drop" class="sidepanel-drop"></div>
        <div class="sidepanel-inner d-flex flex-column">
          <a href="" id="sidepanel-close" class="sidepanel-close d-xl-none"
            >&times;</a
          >
          <div class="app-branding text-center">
            <a class="app-logo" href=""
              ><img
                class="logo-icon"
                style="width: 90px"
                src="{{ url_for('static', filename='images/logotik.png') }}"
                alt="logo"
            /></a>
          </div>

          <div class="text-center mb-3">
            <span
              class="badge px-2 text-capitalize"
              style="background-color: #128c9b"
              >{{ current_user.role }}</span
            >
          </div>

          <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
            <ul class="app-menu list-unstyled accordion" id="menu-accordion">
              <li class="nav-item d-none" id="menu-lecturer">
                <a
                  class="nav-link"
                  id="lecturer"
                  href="{{ url_for('dashboard.lecturer')  }}"
                >
                  <span class="nav-icon">
                    <svg
                      width="1em"
                      height="1em"
                      viewBox="0 0 16 16"
                      class="bi bi-file-person"
                      fill="currentColor"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M12 1H4a1 1 0 0 0-1 1v10.755S4 11 8 11s5 1.755 5 1.755V2a1 1 0 0 0-1-1zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"
                      />
                      <path
                        fill-rule="evenodd"
                        d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
                      />
                    </svg>
                  </span>
                  <span class="nav-link-text">Dosen</span>
                </a>
              </li>
              <li class="nav-item d-none" id="menu-user">
                <a
                  class="nav-link"
                  id="user"
                  href="{{ url_for('dashboard.user')  }}"
                >
                  <span class="nav-icon">
                    <svg
                      width="1em"
                      height="1em"
                      viewBox="0 0 16 16"
                      class="bi bi-card-list"
                      fill="currentColor"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"
                      />
                      <path
                        fill-rule="evenodd"
                        d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"
                      />
                      <circle cx="3.5" cy="5.5" r=".5" />
                      <circle cx="3.5" cy="8" r=".5" />
                      <circle cx="3.5" cy="10.5" r=".5" />
                    </svg>
                  </span>
                  <span class="nav-link-text">Pengguna</span>
                </a>
              </li>
              <li class="nav-item d-none" id="menu-classifier">
                <a
                  class="nav-link"
                  id="classifier"
                  href="{{ url_for('dashboard.classifier')  }}"
                >
                  <span class="nav-icon">
                    <svg
                      width="1em"
                      height="1em"
                      viewBox="0 0 16 16"
                      class="bi bi-files"
                      fill="currentColor"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M4 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H4z"
                      ></path>
                      <path
                        d="M6 0h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2v-1a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1H4a2 2 0 0 1 2-2z"
                      ></path>
                    </svg>
                  </span>
                  <span class="nav-link-text">Inferensi</span>
                </a>
              </li>
              <li class="nav-item d-none" id="menu-history">
                <a
                  class="nav-link"
                  id="history"
                  href="{{ url_for('dashboard.history', id=current_user.id) }}"
                >
                  <span class="nav-icon">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-clock-history"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M8.515 1.019A7 7 0 0 0 8 1V0a8 8 0 0 1 .589.022zm2.004.45a7 7 0 0 0-.985-.299l.219-.976q.576.129 1.126.342zm1.37.71a7 7 0 0 0-.439-.27l.493-.87a8 8 0 0 1 .979.654l-.615.789a7 7 0 0 0-.418-.302zm1.834 1.79a7 7 0 0 0-.653-.796l.724-.69q.406.429.747.91zm.744 1.352a7 7 0 0 0-.214-.468l.893-.45a8 8 0 0 1 .45 1.088l-.95.313a7 7 0 0 0-.179-.483m.53 2.507a7 7 0 0 0-.1-1.025l.985-.17q.1.58.116 1.17zm-.131 1.538q.05-.254.081-.51l.993.123a8 8 0 0 1-.23 1.155l-.964-.267q.069-.247.12-.501m-.952 2.379q.276-.436.486-.908l.914.405q-.24.54-.555 1.038zm-.964 1.205q.183-.183.35-.378l.758.653a8 8 0 0 1-.401.432z"
                      />
                      <path
                        d="M8 1a7 7 0 1 0 4.95 11.95l.707.707A8.001 8.001 0 1 1 8 0z"
                      />
                      <path
                        d="M7.5 3a.5.5 0 0 1 .5.5v5.21l3.248 1.856a.5.5 0 0 1-.496.868l-3.5-2A.5.5 0 0 1 7 9V3.5a.5.5 0 0 1 .5-.5"
                      />
                    </svg>
                  </span>
                  <span class="nav-link-text">Riwayat</span>
                </a>
              </li>
              <li class="nav-item d-none" id="menu-file">
                <a
                  class="nav-link"
                  id="file"
                  href="{{ url_for('dashboard.file') }}"
                >
                  <span class="nav-icon"
                    ><svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-file-earmark"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"
                      />
                    </svg>
                  </span>
                  <span class="nav-link-text">Berkas</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <div class="app-wrapper">
      <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="container-xl">
          {% block content %}{% endblock content %}
        </div>
      </div>
    </div>

    {% block modal %}{% endblock modal %}

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="{{ url_for('static', filename='plugins/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.min.js') }}"></script>
    <script>
      var menu;

      if ("{{ current_user.role }}" === "admin") {
        menu = ["lecturer", "user"];
      } else if ("{{ current_user.role }}" === "pengguna") {
        menu = ["classifier", "history", "file"];
      }

      $.each(menu, function (index, value) {
        $(`#menu-${value}`).removeClass("d-none");
      });

      $("#{{ page }}").addClass("active");

      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, (title, message) in messages %}
            Swal.fire({
              title: '{{ title }}',
              text: '{{ message }}',
              icon: '{{ category }}',
              confirmButtonText: 'Baik, saya mengerti',
              customClass: {
                confirmButton: 'swt-alert-btn'
              }
            })
          {% endfor %}
        {% endif %}
      {% endwith %}

      function alertMessage(title, message, category){
        Swal.fire({
          title: title,
          text: message,
          icon: category,
          confirmButtonText: 'Baik, saya mengerti',
          customClass: {
            confirmButton: 'swt-alert-btn'
          }
        })
      }
    </script>

    <script src="{{ url_for('static', filename='js/app.js') }}"></script>

    <script>
      if ("serviceWorker" in navigator) {
        navigator.serviceWorker
          .register("{{ url_for('static', filename='service-worker.js') }}")
          .then((registration) => {
            console.log(
              "Service Worker registered with scope:",
              registration.scope
            );
          })
          .catch((error) => {
            console.error("Service Worker registration failed:", error);
          });
      }
    </script>
    {% block script %}{% endblock script %}
  </body>
</html>